import type { Metadata } from "next";
import "./globals.css";
import { type_second } from "../functions/fonts";
import Header from "@/components/header";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={type_second.variable}>
        <div className="App">
          <Header />
          <main className="AppBody">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
